braingourmets/currency_select

Gemfile, Gemfile.lock, currency_select.gemspec
Support for rails 4.2.
Note - I didn't make these commits - I noticed on the "network" that @newstler had already done this so I just merged his commits.
=> Rails 4.2 support

README.md
=> [TASK] Recommend installation from rubygems.org instead of GitHub

CHANGELOG.md, Gemfile, currency_select.gemspec
- include the gemspec file in the Gemfile
- require-dev rspec-rails instead of the old rspec
=> [BUGFIX] Fix the Gemfile

spec/currency_select_spec.rb
This removes the deprecation warnings.
=> [TASK] Convert the old "should" spec syntax to the new "expect" syntax

CHANGELOG.md, CODE_OF_CONDUCT.md, README.md
=> [TASK] Add a code of conduct

CHANGELOG.md, Gemfile, Rakefile, currency_select.gemspec, gemfiles/Gemfile.rails-4-2, gemfiles/Gemfile.rails-5-0, gemfiles/Gemfile.rails-5-1, lib/currency_select.rb, rails/init.rb, spec/currency_select_spec.rb, spec/spec_helper.rb
This will improve performance for newer Ruby versions.
=> [TASK] Mark all Ruby files as frozen_string_literal: true

README.md
=> [TASK] Add a list of maintainers to the README

currency_select.gemspec
- add CODE_OF_CONDUCT.md
- remove the tests files
=> [TASK] Clean up the files list in the gemspec

CHANGELOG.md
=> [TASK] Add a changelog entry for the last change

CHANGELOG.md, currency_select.gemspec
=> [BUGFIX] Fix file names references from the gemspec file

.travis.yml, gemfiles/Gemfile.rails-5-2, gemfiles/Gemfile.rails-6-1
Also update the used Rails versions for 5.2 and 6.0.
=> [TASK] Run the CI with Rails 6.1

.github/workflows/publish.yml, CHANGELOG.md
=> [FEATURE] Add automatic gem release

.gitignore
- add leading slashes
- remove obsolete entries
- add entries relevant to local gem installs
=> [TASK] Rework the `.gitignore`

.github/workflows/ci.yml, .rubocop.yml, CHANGELOG.md, currency_select.gemspec
=> [TASK] Drop support for Ruby 2.6

.github/workflows/ci.yml, .rubocop.yml, CHANGELOG.md, currency_select.gemspec, gemfiles/rails-5.2.gemfile
=> [TASK] Drop support for Rails 5.2

.github/workflows/ci.yml, .github/workflows/publish.yml
This change includes the latest security releases for Ruby.
=> [TASK] Update the Ruby versions on CI

.github/dependabot.yml
=> [FEATURE] Configure Dependabot to upgrade the GitHub Actions

.github/workflows/ci.yml, .github/workflows/publish.yml
=> [TASK] Upgrade the GitHub runners to Ubuntu 22.04

CHANGELOG.md, currency_select.gemspec
=> [BUGFIX] Add missing files to the gemspec file

.github/workflows/ci.yml, .rubocop.yml, CHANGELOG.md, currency_select.gemspec, gemfiles/rails-6.0.gemfile
=> [TASK] Drop support for Rails 6.0

.github/workflows/ci.yml, .github/workflows/publish.yml, CHANGELOG.md
=> [FEATURE] Add official support for Ruby 3.3

.github/workflows/ci.yml
=> [TASK] Add bundler caching to the CI

.github/workflows/ci.yml, .github/workflows/publish.yml
=> [TASK] Switch the Ubuntu CI runners to 24.04

.rubocop.yml, currency_select.gemspec
=> [TASK] Update RuboCop and friends

.github/workflows/ci.yml
https://github.com/ruby/ruby/releases/tag/v3_2_5
=> [TASK] Update CI to Ruby 3.2.5

.github/workflows/ci.yml, .github/workflows/publish.yml
https://github.com/ruby/ruby/releases/tag/v3_3_7
https://github.com/ruby/ruby/releases/tag/v3_4_1
=> [TASK] Bump the Ruby versions for CI

.github/workflows/ci.yml, .rubocop.yml, CHANGELOG.md, currency_select.gemspec
https://endoflife.date/ruby
Fixes #190
=> [TASK] Drop support for Ruby 3.1
